# This is an arbitrary title for the config
title = "Borg (Brooks's Org Format)"

# This is a list of all file extensions supported by this config
exts = ["org"]

# The Regex details for flashcard-style questions
# "- (.*) :: ([\s\S]*?)(?=\n\s*[-*0-9]+)"
[flash]
leader = "- "
term = ".*"
separator = " :: "
definition = "[\\s\\S]*?"
terminator = "(?=\n\\s*[-*0-9]+)"